-- 코드를 입력하세요
SELECT
A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) TOTAL_SALES

FROM
BOOK B, AUTHOR A, BOOK_SALES S

WHERE
B.AUTHOR_ID = A.AUTHOR_ID
AND
S.BOOK_ID = B.BOOK_ID
AND
S.SALES_DATE LIKE '2022-01%'

GROUP BY
CATEGORY, B.AUTHOR_ID

ORDER BY
B.AUTHOR_ID, B.category DESC