SELECT
I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) SCORES

FROM
REST_INFO I
JOIN
REST_REVIEW R
ON
I.REST_ID = R.REST_ID

WHERE
I.ADDRESS LIKE '서울%'

GROUP BY
REST_ID
ORDER BY
SCORES DESC, I.FAVORITES DESC