SELECT DR_NAME, DR_ID, 
    CASE 
        WHEN MCDP_CD = 'CS' THEN 'CS'
        WHEN MCDP_CD = 'GS' THEN 'GS'
    END AS MCDP_CD, 
DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") AS HIRE_YMD

FROM DOCTOR

WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'

ORDER BY HIRE_YMD DESC, DR_NAME ASC;